### PR TITLE
add option to control which panels appear by default

### LINKED ISSUE #7: option to configure which panel(s) are opened by default
I'd like to open the right panel by default instead of the left, or have an option to not open either panel automatically when Neovim starts.

### PR DESCRIPTION
**Pull request by mrjones2014**
Fixes #7

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
thnx!

**Comment by ldelossa** [comment]
Should this be able to specify "both" as well, both left and right?

**Comment by mrjones2014** [comment]
Ah yeah, true. I can add that shortly.

**Comment by mrjones2014** [comment]
done 👍

**Comment by ldelossa** [comment]
Just needs a comment update, then merged.

**Comment by ldelossa** [comment]
🚀

**Pull request merged**
