### PR TITLE
chore: change `nvim-ide.txt` to `nvim-ide.md`

### PR DESCRIPTION
**Pull request by W-Mai**
rename `docs/nvim-ide.txt`

### CODE REVIEW

**Comment by mrjones2014** [comment]
Won't this make it so we can't do `:h nvim-ide`??

**Comment by mrjones2014** [comment]
Though, to be fair, I generally try to _generate_ my `doc/*.txt` files from markdown, you can see how I do it here:

- [Makefile command](https://github.com/mrjones2014/legendary.nvim/blob/master/Makefile#L26)
- Which runs [this Lua script](https://github.com/mrjones2014/legendary.nvim/blob/master/vimdoc-gen.lua) in Neovim

**Comment by ldelossa** [comment]
I don't see why this would change to markdown? Also I don't immediately see a need to gen from markdown. Call me old fashion, but the flat txt file seems to work fine in almost all cases when viewing from inside Neovim, no?

**Comment by mrjones2014** [comment]
Yeah, but I've seen on reddit and etc. that a lot of users don't use `:h plugin` and instead go to the plugin's repo on github to view the docs. That's the motivation for me to gen from markdown, also I just prefer writing in markdown.

I think this is partially because there's a good number of plugins that don't provide any `doc/*.txt` file, but `:h plugin` is still my first instinct personally.

**Comment by ldelossa** [comment]
aha, I can see the usefulness of it with that explanation. If the community wants this, I'm not too opposed, as long as the neovim native help tags work correctly.

**Comment by W-Mai** [comment]
> Yeah, but I've seen on reddit and etc. that a lot of users don't use `:h plugin` and instead go to the plugin's repo on github to view the docs. That's the motivation for me to gen from markdown, also I just prefer writing in markdown.
> 
> I think this is partially because there's a good number of plugins that don't provide any `doc/*.txt` file, but `:h plugin` is still my first instinct personally.

yes, It was for this reason that I wanted to modify this file, because when I opened it on GitHub, it didn't have any format and was very inconvenient to read. 
And, when I didn't install the current plug-in, I didn't know if the current plug-in was right for me. 
At this time, reading markdown online is easier to accept than plaint text.

**Comment by mrjones2014** [comment]
> aha, I can see the usefulness of it with that explanation. If the community wants this, I'm not too opposed, as long as the neovim native help tags work correctly.

Help tags work correctly using the tools I've linked in my previous comment. Occasionally you'll get duplicate tags and just have to use lua comment annotations to resolve duplicate tags, but that's the only issue I've experienced.

**Comment by ldelossa** [comment]
Okay, I think i'd approve this if the generate to txt stuff was in here as well, and everything continues to work for bother users who want the in-neovim help, and those who want the markdown help.

**Comment by ldelossa** [comment]
SGTM.

**Comment by technicalpickles** [comment]
As an alternative, I tweaked the highlighting in https://github.com/ldelossa/nvim-ide/pull/63

**Comment by technicalpickles** [comment]
Looks like there are a few options:

- https://github.com/FooSoft/md2vim
- https://github.com/mklabs/vim-markdown-helpfile

It shouldn't be too much of a lift to get that running on in a GitHub Action

**Comment by mrjones2014** [comment]
Yeah, I’ve got a plan for this. I’m planning to tackle it soon, but I didn’t have a chance this weekend.

**Comment by ldelossa** [comment]
hey @W-Mai I probably won't merge this until there's some automation way to move from the .txt file to the markdown. Going to close for now, but if you want to hack something together for this, feel free to re-open with this. 

I'm not a user of web-based markdown help, so I expect this to come from someone who needs it more then I do.

**Pull request closed without merging**
