### PR TITLE
Implement configurable panel sizes

### LINKED ISSUE #13: Default panel width
I've found a few "issues" while testing and i'm adding them individually so as to keep the discussions focused. 

Is it possible to set a wider default width for the panels?

### PR DESCRIPTION
**Pull request by distek**
Fixes #13 

Let me know if this feels okay to you and I'll fix up the documentation.

### CODE REVIEW

**Review by ldelossa — COMMENTED** [review]
Looks pretty good, the "top" panel is going to be deprecated, it works badly, and also VSCode doesn't have one, so you can leave it out.

**Comment by ldelossa** [comment]
Its a bit more of a refactor, but what do you think about opening up the "panels" config object a bit, so we dont spam a bunch of high level panel keys? 

For instance: 

panels = {
  left = { 
    size = 30, 
    panel_group = "explorer"
  }
}

If you dont want to do a larger refactor in this PR, just lmk, and ill merge and refactor it a bit later.

**Comment by distek** [comment]
I like that idea a lot more than how it is currently. I'll look at it in a bit here.

**Comment by distek** [comment]
I thought I had commented on this last night but I guess not.

I might be able to work on the panels config some time this week if you don't get to it.

What I thought I had said last night is, basically, if you're still good with this PR then lets merge it - But now I'm thinking if we end up exposing more config options for the panels themselves, should we bother with this PR?

**Comment by distek** [comment]
Fixed up.

I think I have a way to tackle this in my head so I'll try and attack it tonight if no one else gets to it.

**Comment by ldelossa** [comment]
> I think inability to configure default panel size is a big pain point for this plugin, IMO it should be fixed up (resolve merge conflicts) and merged, and it can be iterated on further.

Agreed 👌

**Comment by mrjones2014** [comment]
My vote would be to merge now and iterate further if needed. Not having this is a big pain point.

**Comment by ldelossa** [comment]
Looks like it needs a rebase.

**Comment by distek** [comment]
No worries!

> Looks like it needs a rebase.
Does it? If so I'll check it out when I get home

**Comment by distek** [comment]
@ldelossa double check me please, but I think we're good now.

**Comment by ldelossa** [comment]
Hey there, I don't think there should be 11 commits in this PR?

**Comment by distek** [comment]
Not sure what I was thinking before. Should be good now.

**Review by ldelossa — APPROVED** [review]

**Comment by ldelossa** [comment]
Thanks!

**Pull request merged**
